image:
  tag: production-latest

testConnection: true

host: 

fullnameOverride: meetingsdk-react-sample
nameOverride: meetingsdk-react-sample


ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"

  hosts:
    - host: 
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: meetingsdk-react-sample
              port:
                number: 80
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 20

replicaCount: 1
